### ISSUE TITLE
Enable local offline development

### ISSUE THREAD

**Issue by marktani** [graphcool/framework#128]
Ideas
* generate mock data for schema to work against

**Comment by changalberto** [comment]
Would be nice to have a way to generate mock data

**Comment by Jesus-Gonzalez** [comment]
I would like to do the following feature request:

*The problem*
I'm using the graph.cool web interface in order to create the project and I'm doing lots of changes. I'm feeling a bit sloppy because I own a 300€ 5 years laptop with a low-end CPU which luckily runs GNU/Linux  but it is not able to run the graph.cool correctly. For example, in the permissions section, when I try to open a modal to edit a permission it takes a long time, around 20 seconds in order to open it, then when I change tabs it's very very slow.
This is not the only problem. I am not able to work with a VCS like `git` and collaborate with my team unless we work in graph.cool in the same time.

*Proposed solution*
I would like to be able to export/download the project to my computer in order to be able to work offline.
It should have a predefined directory hierarchy and source files should be able to include a header in order to include metadata.  
I think I would work faster from my computer using my favourite editor like Atom or vscode.  
It would also be very useful for me to be able to collaborate with teams in some VCS platform like GitHub and then deploy to graph.cool again.


I really like the graph.cool web UI but for a big-scale project with many types, and many permissions and many collaborators it's almost impossible to work. I cannot reverse changes easily, not possible to work with other team members independently, etc..

Thank you very much,  
Jesús

**Comment by marktani** [comment]
The Graphcool Framework comes with a local development cluster: https://blog.graph.cool/introducing-the-graphcool-framework-d9edab2a7816 🎉

**Comment by UADACID** [comment]
I'm always get this message _'You chose the cluster local, but don't have docker initialized, yet.
Please run $ graphcool local up to get a local Graphcool cluster'_

after i run graphcool local up, i get this on pict 
<img width="562" alt="screen shot 2017-10-27 at 5 59 29 pm" src="https://user-images.githubusercontent.com/15373307/32101037-a91e017a-bb40-11e7-9101-2a35fbb02a7a.png">

what is the next step??

**Comment by marktani** [comment]
Please create a new issue to discuss this, @UADACID.
