### ISSUE TITLE
Deployment targets should be service name instead of generated service ID

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#1329]
This proposal removes the service id and introduces name and stage as mandatory meta data for deployed projects

## Deployment target identification

A deployment target is uniquely identified by the combination of

- cluster name
- service name
- stage name

Let's clearly define some terms:

**Cluster**
A cluster is the physical infrastructure that holds data, executes queries and performs data structure migrations.

A cluster can be one of the shared regions operated by Graphcool, a private cluster running on AWS or other hosting provider, or a local development cluster.

The cli needs to know how to connect to the cluster. This information can be provided in two ways:

- `.graphcoolrc` file maintained by the developer
- By the Graphcool Platform

> More information about the Graphcool Platform will be provided in a future spec, but think of it as a version of the current Console that gains the ability to manage organisations and multiple clusters 

**Service name**

Arbitrary name picked by the developer to describe their database service. The combination of stage name and service name is unique on a cluster.

**Stage name**

Arbitrary name picked by the developer, usually used to describe various stages that a service can be deployed to. There is no inherent meaning to the name of stages, but we recommend developers use the usual names `dev`, `staging`, `qa`, and `prod`

## Service endpoints

Service endpoints are generated as follows:

`[cluster-base-url]/[service-name]/[stage]`

For example:

`https://my-prod-cluster.my-company.com/my-webshop-service/prod`
`http://localhost/my-webshop-service/dev`

Endpoint urls are designed to be informational rather than aesthetically pleasing. Developers should use CNAME or other techniques to produce a nice url like `api.my-company.com`

**Comment by kbrandwijk** [comment]
As part of this, I would also ask you to consider this in relation to clusters and targets:
## Services, clusters and stages
Currently, Graphcool has a concept of a service definition, which lives locally and doesn't have any identifier. When deployed, a service definition is deployed to a cluster and gets a generated service id. The deployed service has no concept of 'targets', those are only defined locally. This causes a number of inconveniences, that I would like to address in this proposal:
- Service names are unique. Every time you deploy a service definition (to any shared cluster), you need to come up with a new service name
- Endpoints only use the service id. The only way to 'find' a service by id is by using `graphcool list` to get the service name.
- The most common use case for using multiple 'targets' right now, is for multiple stages (dev, test, prod). On a deployed service, this target concept completely disappears.

This proposal offers a stronger concept from services, clusters and targets.

### Serverless
Serverless uses many of the same concepts that Graphcool uses, but in a slightly different way, that offers some benefits that could easily be applied to Graphcool, so this proposal is heavily inspired by it.

### Single service name
Serverless uses a single service name across all stages (targets) and regions (clusters). This makes endpoint urls a lot more predictable, and easy to reason about it. To apply this concept to Graphcool, I propose the following changes:
- Define service name in `graphcool.yml`
- Use service name instead of generated service id for endpoint urls
- Include region in url for shared clusters
- Include stage in url
Example: `https://api.eu-west-1.graph.cool/dev/my-service`
Also related: #907 

### Production
I think production deployment should not have a stage in the url. For example, the production url for `my-service` should be: `https://api.eu-west-1.graph.cool/my-service`, not `https://api.eu-west-1.graph.cool/prod/my-service`. _TODO_: Define how this can be specified.

### CDN/Nearest cluster
It should be possible to deploy the same service to multiple regions (shared clusters), and benefit from it automatically, by redirecting visitors to the nearest cluster. For example, if you deploy a service to eu-west-1 and us-east-2, accessing your endpoint via `https://api.graph.cool/dev/my-service` should redirect to the nearest cluster. AWS calls this 'latency based routing', Zeit has a similar concept.

### Keeping target (stage) information in deployed services
If a deployed service is aware of the stage it belongs to, this can be useful for grouping services together by stage in a dashboard, or other tools (like logging etc.). See #738 

### Account names?
Moving from service id's to service name creates a new issue. Service names are now unique per account. However, when using service names for endpoint URL's, this means that a service name would need to be unique across the entire platform. This is (probably) an undesirable side-effect. This could be dealt with by including an account name (or customer alias) in the endpoint URL. See #269.

### Terminology
'Target' is a very loose concept. I think that using the term 'stage' makes it more evident what targets actually are. See #956.

**Comment by sorenbs** [comment]
Thanks @kbrandwijk! I have updated the spec. Aa few comments:

### Production

We might introduce this in the future

### CDN/Nearest cluster

Out of scope for this spec

### Keeping target (stage) information in deployed services

Agree - this is included in the spec

### Storing target information locally

Agree - the service-specific `.graphcoolrc` is now obsolete. The global `.graphcoolrc` is still required to specify cluster connection information when you are not using the Platform (Most people will, even when using private clusters or the open source release)

### Deployment

I don't want to introduce the concept of regions at this moment. There will be 3 shared clusters that happen to be deployed in different data centers. It is possible to create a similar setup with private clusters.

### Account names?

You are raising a valid concern. Service name+stage is now unique per cluster. When a private cluster is connected to Graphcool Platform, the service name+stage combination should not be unique across the entire platform. We will probably introduce an organisation concept.
