### ISSUE TITLE
More Constraints

### ISSUE THREAD

**Issue by sorenbs** [graphcool/framework#23]
Make field constraints much more flexible.
This feature can probably be delivered in smaller chunks

**Use case 1**

A phone number field should match a regex

**Use case 2**

A phone number field should be required if and only if the roles field is STORE_MANAGER

**Use case 3**

A money field should only allow prime numbers

**Comment by OlegIlyenko** [comment]
I have another use-case: email and URL validation. I think these are pretty common so it would be nice to have a dedicated validators for them (though it is possible to express it via regexp)

**Comment by marktani** [comment]
Might be also handled by pre-mutation function calls

**Comment by ejoebstl** [comment]
Thoughts: 

- This approach somehow breaks the typing approach of graphql, since an mutation might still fail even if the data types were correct. On the other side, that's a general problem of universal data types like strings. 
- You will only be able to map very basic use cases to regex. Especially, this kind of validation does not take other nodes into account. On the other side, regex is well understood, simple and fast. 
- I very much like the idea of pre-mutation hooks as in #58 for more complex validation cases.

**Comment by georgelovegrove** [comment]
@ejoebstl Massive one up on pre-mutation hooks. Would complete the ability to do any logic you need before mutating something.

**Comment by marktani** [comment]
Another common use case:
* a String should not be empty 

more inspiration: https://github.com/aldeed/meteor-simple-schema

**Comment by marktani** [comment]
Another use case:
* unicity across models #24

**Comment by PierBover** [comment]
What about a constrain that specifies that if a type has 3 fields, at least one of them must be non null.

For example a `Customer` type wth these fields where at least one is required:
* `Individual`
* `Organization`
* `School`

**Comment by kbrandwijk** [comment]
Also see: https://github.com/APIs-guru/graphql-constraints-spec, maybe that's relevant for these use cases?

**Comment by marktani** [comment]
Closing in favor of #728.
