### ISSUE TITLE
Access currently authenticated user in queries

### ISSUE THREAD

**Issue by FredyC** [graphcool/framework#355]
I know it's possible to do queries like...
```
query CurrentUser {
  user { id }
}
```
However, when I need to use that ID in some other query, it has to come in form of a variable which creates more bloated client code. Considering that Graphcool server has access to it based on authentication token and it's already allowing to do it for permission queries, why not to provide it to regular queries?

```
query CurrentUserPosts {
  posts(filter: { authorId: $authenticatedUserId }) { id }
}
```

**Comment by danmkent** [comment]
That would fail graphql validation (either on client or server side) because all variables used in the query have to be defined as per the spec:

https://facebook.github.io/graphql/#sec-All-Variable-Uses-Defined

The usual way to add custom functionality to graphql would be with a directive, but the spec doesn't allow directives to be added inside an argument value (i.e. inside the filter value)

It could possibly work something like this, with a directive on the operation definition which would tell graph.cool to inject the user ID into the `$authenticatedUserId` argument:

```
query CurrentUserPosts($authenticatedUserId:ID!) @injectAuthenticatedUserId {
  posts(filter: { authorId: $authenticatedUserId }) { id }
}
```

**Comment by kbrandwijk** [comment]
@danmkent You're right about the validation, you need the parameter to be defined in the query. However, you don't necessarily need a directive. There could also be a naming convention for the parameter.

**Comment by danmkent** [comment]
quite right - it could be done with a naming convention. I would rather it was not done that way though as I would prefer such injections to be explicit in the query

**Comment by emipc** [comment]
Is it not possible, then? I have to send the userId every time (storing it in the client like the token).

Would be great if we could just send the token.

**Comment by FredyC** [comment]
Obsolete for 1.0 :)
