### ISSUE TITLE
Allow `id`, `createdAt` and `updatedAt` arguments for create mutations

### ISSUE THREAD

**Issue by schickling** [graphcool/framework#365]
When importing data it is a very common scenario to also import existing `id`, `createdAt` and `updatedAt` values. The easiest way to import them is by allowing the corresponding arguments in the create-mutations.

This feature has some implications for the `id` field, which needs to adhere to certain requirements such as being globally unique (needed for Relay's `node` query) and being maximally 25 chars long.

**Comment by marktani** [comment]
This is a superset of https://github.com/graphcool/graphcool/issues/69.

I think providing customizable `createdAt`/`updatedAt` is both more feasible and important than a customizable `id` field, so that could be tackled first. 

When importing data from an existing source I would personally always leave old ids in the `oldId` column, so all ids in Graphcool follow a same structure etc. This has for example the benefit when querying data, the default ordering is `id_DESC`, which orders the items by creation date (that's a nice property of cuids. This property gets lost when using mixed id formats.

On the other hand, customizable ids would also allow you to use your own id format for legacy data AND new data (using `operationBefore`, for example), which is really appealling I think.

**Comment by sorenbs** [comment]
Allowing custom ids also makes it possible to import data from an existing project and maintain the ids.

**Comment by kbrandwijk** [comment]
I think custom id's should only be used when opening up new storage options. So the core of the issue is not overwriting id's. The core is having to migrate data that's in another system, instead of being able to access it directly. Using your own id's is a pandora's box. Are you going to check uniqueness across all types? How will the node(id: "....") query from the Relay endpoint work? Etc.

**Comment by kbrandwijk** [comment]
Thinking about it a bit further, my proposal for ID would be:
- Keep ID field auto-generated for all data stored in the database
- Allow user to specify key(s) on a type (based on unique fields), like this:
```
type MyType implements Node @key(fields: ["compound", "key"]) {
    id: ID!,
    compound: String! @isUnique
    key: Int @isUnique
    ...
}
```
And then generate all queries and mutations not on ID, but on the key fields that are specified. The attribute would be optional, and ID would be the default.

This solves a lot of issues, doing queries, mutations, nested mutations based on a unique field (existing FR), importing oldId fields (existing FR) etc.

**Comment by marktani** [comment]
Continuing discussion in #1278.
