### ISSUE TITLE
Add default permissions when adding a new type

### ISSUE THREAD

**Issue by FredyC** [graphcool/framework#785]
**What is the current behavior?**
When a new type is created within the schema, deployed and then used, I get `Insufficient permissions` errors.

**What is the expected behavior?**
I think there should be some sort of warning as part of deployment process that a created type is missing permissions and won't be accessible aside admin access. This is considerably harder compared to adding/updating types through the Console which took care of creating default permissions for type and relations as well.

Another solution that comes to my mind is a boilerplate generator for types (and some other objects) within CLI. I would just specify a name of the type and it to the schema with basic fields (id, createdAt, updatedAt) and with default permissions (could be separate switch argument). That would make things a lot easier.

**Comment by kbrandwijk** [comment]
I would like some kind of yeoman like generator. I'm building one with snippets for Atom at the moment.

Regarding the permissions. The decision to not have public permissions by default was a deliberate one (https://github.com/graphcool/graphcool/issues/459), because it's easier to forget to lock something down than running into 'Insufficient Permission' on first use.

**Comment by FredyC** [comment]
This is kinda obsolete with 1.0 coming, so I am closing it :)
