### ISSUE TITLE
Recently introduced @module directive breaks latest stable CLI version

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/framework#865]
**What is the current behavior?**
You can't create a project anymore using the latest stable CLI version (1.3.7). Error:
```
The schema is invalid:
  The model `User` is missing the @model directive. Please add it.
```
Because of the error, the local files are not saved, so it's not possible to work around this by changing the schema locally.

**Please share the relevant part of your project (GraphQL schema, functions, permissions, ...) for easier reproduction**
In an empty folder, run `graphcool init`.

**What is the expected behavior?**
You should still be able to create a new project using the latest stable CLI version, so the server should still be able to deal with schemas containing `implements Node`. The `@module` change cannot be breaking, until the current CLI beta goes stable.

**Comment by alassiter** [comment]
A workaround I used tonight, is to create a `something.graphql` file and give it a basic schema with the @model directive. 

In my case, I'm going through the tutorial so my `.graphql` file looked like this:

```
type Link @model {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  url: String!
  description: String!
}
```

Then I ran `graphcool init --schema something.graphql --name Hackernews` and it was able to create the project.graphcool file so that I could continue with the tutorial.

**Comment by kbrandwijk** [comment]
As far as I know, the Framework is no longer in preview, and 1.3.7 is no longer the latest stable version, so this issue is probably outdated now.

**Comment by alassiter** [comment]
@kbrandwijk I just tried `graphcool init` in a new directory. While it doesn't create the error, the resulting project.graphcool file doesn't contain the @model next to the Type. If I pull, it replaces my project.graphcool with a correct version.

That may be by design, just following up on this issue. Thanks!

**Comment by kbrandwijk** [comment]
@alassiter Which graphcool version are you using?

**Comment by alassiter** [comment]
it says 1.3.7 when i run `graphcool version`

**Comment by kbrandwijk** [comment]
Outdated, because the latest version of the CLI now also works with `@model` only.
